### ISSUE TITLE
Add Stop Loss order support to matchengine

### ISSUE THREAD

**Issue by cemkod** [cemkod/viabtc_exchange_server#1]
A stop loss order is an order specifies that an investor wants to execute a trade for a given stock, but only if a specified price level is reached during trading. More info can be found at https://www.investopedia.com/ask/answers/06/stoplossorderdetails.asp

Currently matchengine only supports market and limit orders.

**Comment by ghost** [comment]
Interesting since I was going to write a similar piece of code for currency trading. Since you have a bounty any specific options you want included such for options trading triple weds warning etc.

**Comment by cemkod** [comment]
I will be using it for cryptocurrency trading as well. All I want for the bounty is basic stop-loss order which is a market order with a condition attached that says "this order shall only execute when price drops below X". In other words sell at the best market price when price drops below X.

**Comment by ghost** [comment]
Email me at tekcomm at gmail . com since I am interested in the same I will
take the eth bounty you have up and code it in this week.

**Comment by ghost** [comment]
Ill code it this week and post it up in the repo @
https://github.com/tekcomm/viabtc-viabtc_exchange_server_Auto_Trader

**Comment by rahulpat** [comment]
Interested in this bounty, does this not compile on OSX ?

**Comment by cemkod** [comment]
To be frank, I have never tried compiling it on any platform other than GNU/Linux x86_64. You can always run it on a virtual machine though.

**Comment by kevinobama** [comment]
It seems that It's good. Does anyone try Stop Loss order already when u are  trading?

**Comment by bookmoons** [comment]
I have something toward this. It's in the API and storing on the order book.

```
1, 1539716024.999988, {"method": "update_balance", "params": [1, "BTC", "deposit", 889, "100", {"id": 889}]}
2, 1539717601.789966, {"method": "stop_loss_order", "params": [1, "BTCBCH", 1, "100", "1", "0.01", "TestSource"]}
3, 1539719196.098374, {"method": "stop_loss_order", "params": [1, "BTCBCH", 1, "100", "1", "0.01", "TestSource"]}
4, 1539719196.779019, {"method": "stop_loss_order", "params": [1, "BTCBCH", 1, "100", "1", "0.01", "TestSource"]}
```

Execution triggering is left. Might have it ready tomorrow if things go well.

**Comment by bookmoons** [comment]
Got a branch where triggering is functional:
https://github.com/bookmoons/viabtc_exchange_server/tree/bookmoons/stoploss

There's a gist that sets up the right conditions and runs a test. User 1 adds a stop loss order to sell 100, user 2 performs a market order that triggers it. User 1 ends up with 100 less after the market order:
https://gist.github.com/bookmoons/afad68ec11d5d3cf16e4301c2e563201

There's something around closing/finishing orders that I need to handle. Think that's about the last thing. Will be submitting a pull request soon.

**Comment by cemkod** [comment]
Sounds great. Thank you for your work!

**Comment by bookmoons** [comment]
@cemkod Can I ask for clarification on a point. I'm finding conflicting definitions of _market price_. For example [here](http://www.businessdictionary.com/definition/market-price.html):

>1. General: Unique price at which buyers and sellers agree to trade in an open market at a particular time. In formal markets (such stock exchanges) there are two market prices: the offer (selling) price which is higher, and bid (buying) price that is lower.

>4. Securities trading: Current market price as indicated by the latest recorded trade.

So its either the last trade, or the 2 inside orders on the book. If it's the inside orders then triggering could happen even if no trades occur. Which one should I be using?

**Comment by cemkod** [comment]
the second one.

**Comment by bookmoons** [comment]
Copy that.
